config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Read all tasks
  get "tasks", to: "tasks#index"

  # Create one restaurant(2 routes)
  get "tasks/new", to: "tasks#new", as: :new_task
  post "tasks", to: "tasks#create"

  # Read one task
  get "tasks/:id", to: "tasks#show", as: :task

  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task

  patch "tasks/:id", to: "tasks#update"

  delete "tasks/:id", to: "tasks#destroy", as: :delete_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show

  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit

  end

  def update
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end


  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="form-group">
  <%= form_for @task do |t| %>
    <%= t.label :title, value: "Title" %>
    <%= t.text_field :title %>
    <%= t.label :details, value: "Details" %>
    <%= t.text_field :details %>
    <% unless t.object.new_record? %>
      <%= t.check_box :completed %> Completed
    <% end %>
    <%= t.submit %>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<h2>Edit task</h2>

<%= render "form" %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<ul>
<% @tasks.each do |task| %>
  <%= link_to task_path(task) do %>
    <% if task.completed %>
      <li><i class="far fa-check-square"></i> <%= task.title %> <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, delete_task_path(task),
      method: :delete,
      data: { confirm: "Are you sure?" } %></li>
    <% else %>
      <li><i class="far fa-square"></i> <%= task.title %> <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, delete_task_path(task),
      method: :delete,
      data: { confirm: "Are you sure?" } %></li>
    <% end %>
  <% end %>
<% end %>
</ul>

<%= link_to '<i class="fas fa-plus"> Add a new task </i>'.html_safe, new_task_path %>

app/views/tasks/new.html.erb
<h2>New task</h2>

<%= render "form" %>

app/views/tasks/show.html.erb
<h2><%= @task.details %></h2>

<%= link_to "Edit", edit_task_path %>

<%= link_to "Back to list", tasks_path %>